KhuncaysNews/KhuncaysNews/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("news/", include("news.urls", namespace="news")),
    path("", views.start),
    path('admin/', admin.site.urls),
]

KhuncaysNews/news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path(
        "post/<slug:slug_name>",
        views.post,
        name="post"
    ),
    path(
        "category/<str:category>",
        views.category_post,
        name="category"
    ),
    path(
        "delete/<int:delete_id>",
        views.delete,
        name="delete"
    ),
    path(
        "update/<int:update_id>",
        views.update,
        name="update"
    ),
    path(
        "add",
        views.add,
        name="add"
    ),
    path(
        "profile",
        views.profile,
        name="profile"
    ),
    path(
        "",
        views.home,
        name="home"
    )
]

KhuncaysNews/news/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class NewsModel(models.Model):
    title = models.CharField(
        max_length=200,
        
    )
    content = models.TextField()
    category = models.CharField(
        max_length=50
    )
    published = models.DateTimeField(
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True
    )
    slug = models.SlugField(
        blank=True,
        max_length=50,
        editable=False
    )

    def __str__(self):
        return f"{self.id}. {self.title}"
    
    def save(self):
        self.slug = slugify(self.title)
        super().save()

KhuncaysNews/news/forms.py
from django import forms
from .models import NewsModel

class NewsForm(forms.ModelForm):
    class Meta:
        model = NewsModel
        fields = [
            "title",
            "content",
            "category"
        ]
        widgets = {
            "title":forms.TextInput(
                attrs={
                    "class":"form-control",
                    "placeholder":"Input Title"
                }
            ),
            "content":forms.Textarea(
                attrs={
                    "class":"form-control",
                    "placeholder":"Input Content"
                }
            ),
            "category":forms.TextInput(
                attrs={
                    "class":"form-control",
                    "placeholder":"Input Category"
                }
            )
        }

KhuncaysNews/KhuncaysNews/views.py
from django.shortcuts import redirect

def start(request):
    return redirect("news:home")

KhuncaysNews/news/views.py
from django.shortcuts import render, redirect
from .models import NewsModel
from .forms import NewsForm

def home(request):
    models = NewsModel.objects.all()
    categories = NewsModel.objects.values("category").distinct()
    format = {
        "title":"Home",
        "all_data":models,
        "categories":categories
    }
    return render(request, "news/home.html", format)

def add(request):
    forms = NewsForm(request.POST or None)
    if request.method == "POST":
        if forms.is_valid():
            forms.save()
            return redirect("news:home")
    format = {
        "title":"Add News",
        "forms":forms
    }
    return render(request, "news/add.html", format)

def post(request, slug_name):
    get_data = NewsModel.objects.get(slug__iexact=slug_name)
    format = {
        "title":slug_name,
        "data":get_data
    }
    return render(request, "news/post.html", format)

def update(request, update_id):
    data_target = NewsModel.objects.get(id=update_id)
    current_data = data_target.__dict__
    forms = NewsForm(
        request.POST or None,
        initial=current_data,
        instance=data_target
    )
    if request.method == "POST":
        if forms.is_valid():
            forms.save()
            return redirect("news:home")
    format = {
        "title":"Update News",
        "forms":forms,
        "data":data_target
    }
    return render(request, "news/update.html", format)

def delete(request, delete_id):
    data_target = NewsModel.objects.get(id=delete_id).delete()
    return redirect("news:home")

def category_post(request, category):
    data_filtered = NewsModel.objects.filter(category__iexact=category)
    format = {
        "title":category,
        "all_data":data_filtered
    }
    return render(request, "news/category_post.html", format)

def profile(request):
    return render(request, "news/profile.html")

KhuncaysNews/news/templates/news/add.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
    <h1>Add your Post</h1>
    <br><br>
    <form action="" method="post">
        {% csrf_token %}
            {% for form in forms %}
            <div class="form-group">
                <b>
                    {{form.label}}
                </b>
                {{form}}
                <br><br>
            </div>
            {% endfor %}
        <br>
        <button type="submit" class="btn btn-success">
            Post
        </button>
    </form>
    <br><br><br>
{% endblock content %}

KhuncaysNews/news/templates/news/category_post.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
    <h1>News Categorized by "{{title}}"</h1>
    <h5>Enjoy our fresh news</h5>
    <hr>
    <br><br>
        {% for data in all_data %}
            <a href="{% url 'news:post' data.slug %}" class="nav-link"><h3>{{data.title}}</h3></a>
            <p>{{data.published}}</p>
        {% endfor %}
    <a href="{% url 'news:home' %}" class="btn btn-success">Back</a>
{% endblock content %}

KhuncaysNews/news/templates/news/home.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
    <h1>Welcome !</h1>
    <h5>Enjoy our fresh news</h5>
    <hr>
    <ul class="nav">
        {% for data in categories %}
        <li>
            <a href="{% url 'news:category' data.category %}" class="nav-link">{{data.category}}</a>
        </li>
        {% endfor %}
    </ul>
    <br><br>
        {% for data in all_data %}
            <a href="{% url 'news:post' data.slug %}"><h3>{{data.title}}</h3></a>
            <p>{{data.published}}</p>
            <br>
        {% endfor %}
{% endblock content %}

KhuncaysNews/news/templates/news/post.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
    <h1>{{title}}</h1>
    <hr>
    <br>
    <p>{{data.content}}</p>
    <br><br>
    <b>Published on: {{data.published}}</b>
    <br>
    <b>Updated on  : {{data.updated}}</b>
    <hr>
    <a href="{% url 'news:home' %}" class="btn btn-success">Back</a>
    <a href="{% url 'news:update' data.id %}" class="btn btn-warning">Update</a>
    <a href="{% url 'news:delete' data.id %}" class="btn btn-danger">Delete</a>
{% endblock content %}

KhuncaysNews/news/templates/news/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Andrean</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/media.css' %}" />
  </head>
  <body>
    <nav id="desktop-nav">
      <div class="logo">Andrean Gusman Djabbar</div>
      <div>
        <ul class="nav-links">
          <li><a href="{% url 'news:home' %}">Home</a></li>
          <li><a href="{% url 'news:add' %}">Add</a></li>
          <li><a href="{% url 'news:profile' %}">About Us</a></li>
        </ul>
      </div>
    </nav>
    <nav id="hamburger-nav">
      <div class="logo">Andrean Gusman Djabbar</div>
      <div class="hamburger-menu">
        <div class="hamburger-icon" onclick="toggleMenu()">
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div class="menu-links">
          <li><a href="{% url 'news:home' %}">Home</a></li>
          <li><a href="{% url 'news:add' %}">Add</a></li>
          <li><a href="{% url 'news:profile' %}">About</a></li>
        </div>
      </div>
    </nav>
    <section id="profile">
      <div class="section__pic-container">
        <img src="{% static 'img/Andrean_circle.png' %}" alt="Andrean Picture" />
      </div>
      <div class="section__text">
        <p class="section__text__p1">Hello, I'm</p>
        <h1 class="title">Andrean</h1>
        <p class="section__text__p2">Backend Developer</p>
        <div id="socials-container">
          <a href="https://www.linkedin.com/in/andrean-gusman-djabbar-5734b0276/" target="_blank">
            <img src="{% static 'img/linkedin.png' %}" alt="My LinkedIn profile" class="icon" />
        </a>
        <a href="https://github.com/AndreanDjabbar" target="_blank">
            <img src="{% static 'img/github.png' %}" alt="My Github profile" class="icon" />
        </a>
        </div>
      </div>
    </section>
    <section id="contact">
      <h1 class="title">Contact Me</h1>
      <div class="contact-info-upper-container">
        <div class="contact-info-container">
          <img
            src="{% static 'img/email.png' %}"
            alt="Email icon"
            class="icon contact-icon email-icon"
          />
          <p><a href="mailto:examplemail@gmail.com" target="_blank">Andreanjabar18@gmail.com</a></p>
        </div>
        <div class="contact-info-container">
          <img
            src="{% static 'img/linkedin.png' %}"
            alt="LinkedIn icon"
            class="icon contact-icon"
          />
          <p><a href="https://www.linkedin.com/in/andrean-gusman-djabbar-5734b0276/" target="_blank">Andrean Gusman Djabbar</a></p>
        </div>
      </div>
    </section>
    <footer>
      <nav>
        <div class="nav-links-container">
          <ul class="nav-links">
            <li><a href="{% url 'news:home' %}">Home</a></li>
            <li><a href="{% url 'news:add' %}">Add</a></li>
            <li><a href="{% url 'news:profile' %}">About Us</a></li>
          </ul>
        </div>
      </nav>
      <p>Copyright &#169; 2023 Andrean Gusman Djabbar. All Rights Reserved.</p>
    </footer>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

KhuncaysNews/news/templates/news/update.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
    <h1>Update your Post</h1>
    <br><br>
    <form action="" method="post">
        {% csrf_token %}
            {% for form in forms %}
            <div class="form-group">
                <b>
                    {{form.label}}
                </b>
                {{form}}
                <br><br>
            </div>
            {% endfor %}
        <br>
        <a href="{% url 'news:post' data.slug %}" class="btn btn-danger">Cancel</a>
        <button type="submit" class="btn btn-success">
            Post
        </button>
    </form>
    <br><br><br>
{% endblock content %}

KhuncaysNews/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    {% include "snippets/styles.html" %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><h1>KhuncaysNews</h1></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'news:home' %}"><h5>Home</h5></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:add' %}"><h5>Add</h5></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:profile' %}"><h5>About Us</h5></a>
                </li>
                </ul>
            </div>
            </div>
        </nav>
    <br><br>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    {% include "snippets/scripts.html" %}
</body>
</html>

KhuncaysNews/templates/snippets/scripts.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

KhuncaysNews/templates/snippets/styles.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">